// Plutchik-keyed emotion lexicon — original work, structurally aligned
// with the NRC Emotion Lexicon (Mohammad & Turney, 2013) but written
// fresh to avoid NRC's research-only license. Coverage is tilted toward
// vocabulary that comes up in introspective, body-aware speech (the
// kind of language EMPATHEIA hears) rather than general English. Each
// entry: word → primary emotion + intensity tier.
//
// To add a word: pick the closest primary, then the tier (low/mid/high)
// based on activation. "annoyed" is anger/low, "furious" is anger/high.

import type { PlutchikPrimary, PlutchikIntensity } from "./plutchik"

export interface LexiconEntry {
  word: string
  primary: PlutchikPrimary
  intensity: PlutchikIntensity
}

const RAW: Array<[string, PlutchikPrimary, PlutchikIntensity]> = [
  // ─────────── joy ───────────
  ["happy", "joy", "mid"],
  ["happiness", "joy", "mid"],
  ["glad", "joy", "low"],
  ["pleased", "joy", "low"],
  ["content", "joy", "low"],
  ["contented", "joy", "low"],
  ["calm", "joy", "low"],
  ["peaceful", "joy", "low"],
  ["serene", "joy", "low"],
  ["okay", "joy", "low"],
  ["fine", "joy", "low"],
  ["good", "joy", "low"],
  ["nice", "joy", "low"],
  ["alright", "joy", "low"],
  ["lighter", "joy", "low"],
  ["softening", "joy", "low"],
  ["easing", "joy", "low"],
  ["relieved", "joy", "low"],
  ["relief", "joy", "low"],
  ["safe", "joy", "low"],
  ["joy", "joy", "mid"],
  ["joyful", "joy", "mid"],
  ["delighted", "joy", "mid"],
  ["cheerful", "joy", "mid"],
  ["excited", "joy", "mid"],
  ["upbeat", "joy", "mid"],
  ["bright", "joy", "mid"],
  ["alive", "joy", "mid"],
  ["energized", "joy", "mid"],
  ["lit", "joy", "mid"],
  ["amazing", "joy", "mid"],
  ["awesome", "joy", "mid"],
  ["wonderful", "joy", "mid"],
  ["great", "joy", "mid"],
  ["love", "joy", "mid"],
  ["loved", "joy", "mid"],
  ["loving", "joy", "mid"],
  ["grateful", "joy", "mid"],
  ["thankful", "joy", "mid"],
  ["proud", "joy", "mid"],
  ["confident", "joy", "mid"],
  ["smiling", "joy", "mid"],
  ["beaming", "joy", "mid"],
  ["thrilled", "joy", "high"],
  ["ecstatic", "joy", "high"],
  ["elated", "joy", "high"],
  ["euphoric", "joy", "high"],
  ["overjoyed", "joy", "high"],
  ["radiant", "joy", "high"],
  ["blissful", "joy", "high"],

  // ─────────── trust ───────────
  ["trust", "trust", "mid"],
  ["trusting", "trust", "mid"],
  ["trusted", "trust", "mid"],
  ["accept", "trust", "low"],
  ["accepted", "trust", "low"],
  ["accepting", "trust", "low"],
  ["acceptance", "trust", "low"],
  ["allow", "trust", "low"],
  ["allowed", "trust", "low"],
  ["open", "trust", "low"],
  ["openness", "trust", "low"],
  ["receptive", "trust", "low"],
  ["safe", "trust", "low"],
  ["secure", "trust", "low"],
  ["seen", "trust", "mid"],
  ["heard", "trust", "mid"],
  ["held", "trust", "mid"],
  ["belong", "trust", "low"],
  ["belonged", "trust", "low"],
  ["belonging", "trust", "low"],
  ["close", "trust", "low"],
  ["closeness", "trust", "low"],
  ["intimate", "trust", "mid"],
  ["intimacy", "trust", "mid"],
  ["faith", "trust", "mid"],
  ["faithful", "trust", "mid"],
  ["loyal", "trust", "mid"],
  ["loyalty", "trust", "mid"],
  ["bond", "trust", "mid"],
  ["bonded", "trust", "mid"],
  ["committed", "trust", "mid"],
  ["dedicated", "trust", "mid"],
  ["respect", "trust", "mid"],
  ["respected", "trust", "mid"],
  ["admire", "trust", "high"],
  ["admiration", "trust", "high"],
  ["reverence", "trust", "high"],
  ["devoted", "trust", "high"],
  ["devotion", "trust", "high"],
  ["worship", "trust", "high"],

  // ─────────── fear ───────────
  ["fear", "fear", "mid"],
  ["afraid", "fear", "mid"],
  ["scared", "fear", "mid"],
  ["frightened", "fear", "mid"],
  ["nervous", "fear", "mid"],
  ["anxious", "fear", "mid"],
  ["anxiety", "fear", "mid"],
  ["worried", "fear", "mid"],
  ["worry", "fear", "mid"],
  ["worrying", "fear", "mid"],
  ["uneasy", "fear", "low"],
  ["unease", "fear", "low"],
  ["apprehensive", "fear", "low"],
  ["apprehension", "fear", "low"],
  ["jittery", "fear", "low"],
  ["jumpy", "fear", "low"],
  ["edgy", "fear", "low"],
  ["restless", "fear", "low"],
  ["uncertain", "fear", "low"],
  ["unsure", "fear", "low"],
  ["doubtful", "fear", "low"],
  ["doubt", "fear", "low"],
  ["concerned", "fear", "low"],
  ["concern", "fear", "low"],
  ["panicking", "fear", "high"],
  ["panic", "fear", "high"],
  ["panicked", "fear", "high"],
  ["terrified", "fear", "high"],
  ["terror", "fear", "high"],
  ["dread", "fear", "high"],
  ["dreading", "fear", "high"],
  ["horrified", "fear", "high"],
  ["horror", "fear", "high"],
  ["petrified", "fear", "high"],
  ["spiraling", "fear", "high"],
  ["spiralling", "fear", "high"],
  ["paralyzed", "fear", "high"],
  ["paralysed", "fear", "high"],
  ["overwhelmed", "fear", "high"],
  ["unsafe", "fear", "high"],
  ["threatened", "fear", "mid"],
  ["intimidated", "fear", "mid"],

  // ─────────── surprise ───────────
  ["surprise", "surprise", "mid"],
  ["surprised", "surprise", "mid"],
  ["startled", "surprise", "mid"],
  ["shocked", "surprise", "high"],
  ["stunned", "surprise", "high"],
  ["astounded", "surprise", "high"],
  ["amazed", "surprise", "high"],
  ["dumbfounded", "surprise", "high"],
  ["floored", "surprise", "high"],
  ["speechless", "surprise", "high"],
  ["unexpected", "surprise", "low"],
  ["sudden", "surprise", "low"],
  ["abrupt", "surprise", "low"],
  ["caught off", "surprise", "mid"],
  ["taken aback", "surprise", "mid"],
  ["thrown off", "surprise", "mid"],
  ["wow", "surprise", "mid"],
  ["whoa", "surprise", "mid"],

  // ─────────── sadness ───────────
  ["sad", "sadness", "mid"],
  ["sadness", "sadness", "mid"],
  ["unhappy", "sadness", "mid"],
  ["upset", "sadness", "mid"],
  ["down", "sadness", "low"],
  ["low", "sadness", "low"],
  ["blue", "sadness", "low"],
  ["heavy", "sadness", "low"],
  ["weighed", "sadness", "low"],
  ["pensive", "sadness", "low"],
  ["wistful", "sadness", "low"],
  ["nostalgic", "sadness", "low"],
  ["miss", "sadness", "low"],
  ["missing", "sadness", "low"],
  ["longing", "sadness", "low"],
  ["yearning", "sadness", "low"],
  ["melancholy", "sadness", "low"],
  ["bittersweet", "sadness", "low"],
  ["disappointed", "sadness", "mid"],
  ["disappointment", "sadness", "mid"],
  ["discouraged", "sadness", "mid"],
  ["dejected", "sadness", "mid"],
  ["lonely", "sadness", "mid"],
  ["loneliness", "sadness", "mid"],
  ["alone", "sadness", "mid"],
  ["isolated", "sadness", "mid"],
  ["disconnected", "sadness", "mid"],
  ["abandoned", "sadness", "high"],
  ["rejected", "sadness", "high"],
  ["unloved", "sadness", "high"],
  ["unwanted", "sadness", "high"],
  ["unseen", "sadness", "high"],
  ["invisible", "sadness", "high"],
  ["hopeless", "sadness", "high"],
  ["despair", "sadness", "high"],
  ["despairing", "sadness", "high"],
  ["devastated", "sadness", "high"],
  ["broken", "sadness", "high"],
  ["shattered", "sadness", "high"],
  ["crushed", "sadness", "high"],
  ["grief", "sadness", "high"],
  ["grieving", "sadness", "high"],
  ["mourning", "sadness", "high"],
  ["empty", "sadness", "high"],
  ["hollow", "sadness", "high"],
  ["numb", "sadness", "high"],
  ["depressed", "sadness", "high"],
  ["depression", "sadness", "high"],
  ["worthless", "sadness", "high"],
  ["pointless", "sadness", "mid"],
  ["meaningless", "sadness", "mid"],
  ["hurt", "sadness", "mid"],
  ["hurts", "sadness", "mid"],
  ["hurting", "sadness", "mid"],
  ["aching", "sadness", "mid"],
  ["sore", "sadness", "low"],
  ["raw", "sadness", "high"],
  ["tender", "sadness", "low"],
  ["fragile", "sadness", "mid"],
  ["small", "sadness", "low"],
  ["tiny", "sadness", "low"],
  ["crying", "sadness", "mid"],
  ["weeping", "sadness", "mid"],
  ["tears", "sadness", "mid"],
  ["sobbing", "sadness", "high"],

  // ─────────── disgust ───────────
  ["disgust", "disgust", "mid"],
  ["disgusted", "disgust", "mid"],
  ["disgusting", "disgust", "mid"],
  ["gross", "disgust", "low"],
  ["icky", "disgust", "low"],
  ["yuck", "disgust", "low"],
  ["bored", "disgust", "low"],
  ["boredom", "disgust", "low"],
  ["uninterested", "disgust", "low"],
  ["indifferent", "disgust", "low"],
  ["repulsed", "disgust", "high"],
  ["repulsion", "disgust", "high"],
  ["revolted", "disgust", "high"],
  ["sickened", "disgust", "mid"],
  ["sick", "disgust", "low"],
  ["nauseous", "disgust", "mid"],
  ["nauseated", "disgust", "mid"],
  ["loathing", "disgust", "high"],
  ["loathe", "disgust", "high"],
  ["detest", "disgust", "high"],
  ["hate", "disgust", "high"],
  ["hatred", "disgust", "high"],
  ["abhor", "disgust", "high"],
  ["fed up", "disgust", "mid"],
  ["sick of", "disgust", "mid"],
  ["over it", "disgust", "low"],
  ["done with", "disgust", "mid"],
  ["ashamed", "disgust", "high"],
  ["shame", "disgust", "high"],
  ["embarrassed", "disgust", "mid"],
  ["embarrassment", "disgust", "mid"],
  ["humiliated", "disgust", "high"],
  ["humiliation", "disgust", "high"],
  ["dirty", "disgust", "mid"],
  ["unclean", "disgust", "mid"],
  ["pathetic", "disgust", "mid"],

  // ─────────── anger ───────────
  ["anger", "anger", "mid"],
  ["angry", "anger", "mid"],
  ["mad", "anger", "mid"],
  ["pissed", "anger", "mid"],
  ["frustrated", "anger", "mid"],
  ["frustration", "anger", "mid"],
  ["irritated", "anger", "low"],
  ["irritating", "anger", "low"],
  ["annoyed", "anger", "low"],
  ["annoying", "anger", "low"],
  ["bothered", "anger", "low"],
  ["aggravated", "anger", "mid"],
  ["agitated", "anger", "mid"],
  ["resentful", "anger", "mid"],
  ["resentment", "anger", "mid"],
  ["resent", "anger", "mid"],
  ["bitter", "anger", "mid"],
  ["bitterness", "anger", "mid"],
  ["tense", "anger", "low"],
  ["wound up", "anger", "mid"],
  ["clenched", "anger", "mid"],
  ["furious", "anger", "high"],
  ["fury", "anger", "high"],
  ["livid", "anger", "high"],
  ["enraged", "anger", "high"],
  ["raging", "anger", "high"],
  ["rage", "anger", "high"],
  ["seething", "anger", "high"],
  ["fuming", "anger", "high"],
  ["boiling", "anger", "high"],
  ["incensed", "anger", "high"],
  ["outraged", "anger", "high"],
  ["unfair", "anger", "mid"],
  ["unjust", "anger", "mid"],
  ["unappreciated", "anger", "mid"],
  ["taken for granted", "anger", "mid"],
  ["dismissed", "anger", "mid"],
  ["ignored", "anger", "mid"],
  ["talked over", "anger", "mid"],

  // ─────────── anticipation ───────────
  ["anticipation", "anticipation", "mid"],
  ["anticipating", "anticipation", "mid"],
  ["expecting", "anticipation", "low"],
  ["expectation", "anticipation", "low"],
  ["interested", "anticipation", "low"],
  ["interest", "anticipation", "low"],
  ["curious", "anticipation", "low"],
  ["curiosity", "anticipation", "low"],
  ["engaged", "anticipation", "low"],
  ["focused", "anticipation", "low"],
  ["motivated", "anticipation", "mid"],
  ["determined", "anticipation", "mid"],
  ["driven", "anticipation", "mid"],
  ["eager", "anticipation", "mid"],
  ["keen", "anticipation", "mid"],
  ["hopeful", "anticipation", "mid"],
  ["hope", "anticipation", "mid"],
  ["optimistic", "anticipation", "mid"],
  ["optimism", "anticipation", "mid"],
  ["looking forward", "anticipation", "mid"],
  ["expectant", "anticipation", "mid"],
  ["alert", "anticipation", "high"],
  ["vigilant", "anticipation", "high"],
  ["watchful", "anticipation", "high"],
  ["hyperaware", "anticipation", "high"],
  ["hypervigilant", "anticipation", "high"],
  ["braced", "anticipation", "high"],

  // ─────────── chronic-state cross-category ───────────
  // Words that signal a depleted regulatory state — modeled here as
  // sadness-low so they bias the secondary, not the primary read.
  ["tired", "sadness", "low"],
  ["exhausted", "sadness", "mid"],
  ["drained", "sadness", "mid"],
  ["depleted", "sadness", "mid"],
  ["worn out", "sadness", "mid"],
  ["burnt out", "sadness", "mid"],
  ["burned out", "sadness", "mid"],
  ["spent", "sadness", "low"],
  ["fatigued", "sadness", "low"],
  ["sleepy", "sadness", "low"],

  // Signals of guarded / closed state — sit between fear and disgust.
  ["guarded", "fear", "low"],
  ["defensive", "fear", "low"],
  ["walls up", "fear", "low"],
  ["protective", "fear", "low"],
  ["distrust", "disgust", "low"],
  ["suspicious", "disgust", "low"],
  ["wary", "fear", "low"],

  // Stuck / loop patterns — sadness-mid, also surfaces processing tag.
  ["stuck", "sadness", "mid"],
  ["frozen", "fear", "mid"],
  ["loop", "anticipation", "low"],
  ["replaying", "anticipation", "low"],
  ["replay", "anticipation", "low"],
  ["ruminating", "anticipation", "low"],
  ["overthinking", "anticipation", "mid"],
]

// Build the lookup once. Keys are lowercased single-token or short
// multi-token phrases; the analyzer handles both.
const lookup = new Map<string, LexiconEntry>()
for (const [word, primary, intensity] of RAW) {
  // Last-write wins for duplicates so a deliberate later override (e.g.,
  // a chronic-state remap of "tired") replaces the earlier entry.
  lookup.set(word.toLowerCase(), { word, primary, intensity })
}

export function lookupLexicon(token: string): LexiconEntry | null {
  return lookup.get(token.toLowerCase()) ?? null
}

// Multi-token phrase prefixes — used by the analyzer to greedily match
// before falling back to single-token lookup. Generated automatically.
export const MULTI_TOKEN_PHRASES: string[] = Array.from(lookup.keys())
  .filter((w) => w.includes(" "))
  .sort((a, b) => b.length - a.length)

export function lexiconSize(): number {
  return lookup.size
}
